
cc_library(
    name = "common",
    visibility = ["//visibility:public"],
    srcs = ["LockClass.cpp", "Logger.cpp", "SemaphoreClass.cpp", "SocketClass.cpp", "TCPClient.cpp", "TCPListener.cpp", "ThreadClass.cpp"],
    hdrs = ["LockClass.h", "Logger.h", "SemaphoreClass.h", "SocketClass.h", "TCPClient.h", "TCPListener.h", "ThreadClass.h"],
)